// Code generated by protoc-gen-all. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package maintenance

import (
	"github.com/xhayamix/proto-gen-golang/pkg/domain/enum"
)

func getFeatureMaintenanceTypes(method string) enum.FeatureMaintenanceTypeSlice {
	switch method {
	default:
		return nil
	}
}
