// Code generated by protoc-gen-all. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package maintenance

import (
	"github.com/scylladb/go-set/strset"
)

var disableCheckMaintenanceMethodSet = strset.New()
