// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: server/options/transaction/transaction.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldOption_DDL_ReferenceOption int32

const (
	FieldOption_DDL_RESTRICT  FieldOption_DDL_ReferenceOption = 0
	FieldOption_DDL_CASCADE   FieldOption_DDL_ReferenceOption = 1
	FieldOption_DDL_SET_NULL  FieldOption_DDL_ReferenceOption = 2
	FieldOption_DDL_NO_ACTION FieldOption_DDL_ReferenceOption = 3
)

// Enum value maps for FieldOption_DDL_ReferenceOption.
var (
	FieldOption_DDL_ReferenceOption_name = map[int32]string{
		0: "RESTRICT",
		1: "CASCADE",
		2: "SET_NULL",
		3: "NO_ACTION",
	}
	FieldOption_DDL_ReferenceOption_value = map[string]int32{
		"RESTRICT":  0,
		"CASCADE":   1,
		"SET_NULL":  2,
		"NO_ACTION": 3,
	}
)

func (x FieldOption_DDL_ReferenceOption) Enum() *FieldOption_DDL_ReferenceOption {
	p := new(FieldOption_DDL_ReferenceOption)
	*p = x
	return p
}

func (x FieldOption_DDL_ReferenceOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldOption_DDL_ReferenceOption) Descriptor() protoreflect.EnumDescriptor {
	return file_server_options_transaction_transaction_proto_enumTypes[0].Descriptor()
}

func (FieldOption_DDL_ReferenceOption) Type() protoreflect.EnumType {
	return &file_server_options_transaction_transaction_proto_enumTypes[0]
}

func (x FieldOption_DDL_ReferenceOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldOption_DDL_ReferenceOption.Descriptor instead.
func (FieldOption_DDL_ReferenceOption) EnumDescriptor() ([]byte, []int) {
	return file_server_options_transaction_transaction_proto_rawDescGZIP(), []int{1, 0, 0}
}

type MessageOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ddl *MessageOption_DDL `protobuf:"bytes,2,opt,name=ddl,proto3" json:"ddl,omitempty"`
}

func (x *MessageOption) Reset() {
	*x = MessageOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_options_transaction_transaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOption) ProtoMessage() {}

func (x *MessageOption) ProtoReflect() protoreflect.Message {
	mi := &file_server_options_transaction_transaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOption.ProtoReflect.Descriptor instead.
func (*MessageOption) Descriptor() ([]byte, []int) {
	return file_server_options_transaction_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *MessageOption) GetDdl() *MessageOption_DDL {
	if x != nil {
		return x.Ddl
	}
	return nil
}

type FieldOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ddl *FieldOption_DDL `protobuf:"bytes,2,opt,name=ddl,proto3" json:"ddl,omitempty"`
}

func (x *FieldOption) Reset() {
	*x = FieldOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_options_transaction_transaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOption) ProtoMessage() {}

func (x *FieldOption) ProtoReflect() protoreflect.Message {
	mi := &file_server_options_transaction_transaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOption.ProtoReflect.Descriptor instead.
func (*FieldOption) Descriptor() ([]byte, []int) {
	return file_server_options_transaction_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *FieldOption) GetDdl() *FieldOption_DDL {
	if x != nil {
		return x.Ddl
	}
	return nil
}

type MessageOption_DDL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Indexes []*MessageOption_DDL_Index `protobuf:"bytes,1,rep,name=indexes,proto3" json:"indexes,omitempty"`
}

func (x *MessageOption_DDL) Reset() {
	*x = MessageOption_DDL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_options_transaction_transaction_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageOption_DDL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOption_DDL) ProtoMessage() {}

func (x *MessageOption_DDL) ProtoReflect() protoreflect.Message {
	mi := &file_server_options_transaction_transaction_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOption_DDL.ProtoReflect.Descriptor instead.
func (*MessageOption_DDL) Descriptor() ([]byte, []int) {
	return file_server_options_transaction_transaction_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MessageOption_DDL) GetIndexes() []*MessageOption_DDL_Index {
	if x != nil {
		return x.Indexes
	}
	return nil
}

type MessageOption_DDL_Index struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *MessageOption_DDL_Index) Reset() {
	*x = MessageOption_DDL_Index{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_options_transaction_transaction_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageOption_DDL_Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOption_DDL_Index) ProtoMessage() {}

func (x *MessageOption_DDL_Index) ProtoReflect() protoreflect.Message {
	mi := &file_server_options_transaction_transaction_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOption_DDL_Index.ProtoReflect.Descriptor instead.
func (*MessageOption_DDL_Index) Descriptor() ([]byte, []int) {
	return file_server_options_transaction_transaction_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *MessageOption_DDL_Index) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type FieldOption_DDL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pk              bool                `protobuf:"varint,1,opt,name=pk,proto3" json:"pk,omitempty"`
	Fk              *FieldOption_DDL_FK `protobuf:"bytes,2,opt,name=fk,proto3" json:"fk,omitempty"`
	Size            uint32              `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Nullable        bool                `protobuf:"varint,4,opt,name=nullable,proto3" json:"nullable,omitempty"`
	IsAutoIncrement bool                `protobuf:"varint,5,opt,name=isAutoIncrement,proto3" json:"isAutoIncrement,omitempty"`
	HasDefault      bool                `protobuf:"varint,6,opt,name=hasDefault,proto3" json:"hasDefault,omitempty"`
}

func (x *FieldOption_DDL) Reset() {
	*x = FieldOption_DDL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_options_transaction_transaction_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldOption_DDL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOption_DDL) ProtoMessage() {}

func (x *FieldOption_DDL) ProtoReflect() protoreflect.Message {
	mi := &file_server_options_transaction_transaction_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOption_DDL.ProtoReflect.Descriptor instead.
func (*FieldOption_DDL) Descriptor() ([]byte, []int) {
	return file_server_options_transaction_transaction_proto_rawDescGZIP(), []int{1, 0}
}

func (x *FieldOption_DDL) GetPk() bool {
	if x != nil {
		return x.Pk
	}
	return false
}

func (x *FieldOption_DDL) GetFk() *FieldOption_DDL_FK {
	if x != nil {
		return x.Fk
	}
	return nil
}

func (x *FieldOption_DDL) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FieldOption_DDL) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *FieldOption_DDL) GetIsAutoIncrement() bool {
	if x != nil {
		return x.IsAutoIncrement
	}
	return false
}

func (x *FieldOption_DDL) GetHasDefault() bool {
	if x != nil {
		return x.HasDefault
	}
	return false
}

type FieldOption_DDL_FK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table    string                          `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Column   string                          `protobuf:"bytes,2,opt,name=column,proto3" json:"column,omitempty"`
	OnDelete FieldOption_DDL_ReferenceOption `protobuf:"varint,3,opt,name=onDelete,proto3,enum=server.options.transaction.FieldOption_DDL_ReferenceOption" json:"onDelete,omitempty"`
	OnUpdate FieldOption_DDL_ReferenceOption `protobuf:"varint,4,opt,name=onUpdate,proto3,enum=server.options.transaction.FieldOption_DDL_ReferenceOption" json:"onUpdate,omitempty"`
}

func (x *FieldOption_DDL_FK) Reset() {
	*x = FieldOption_DDL_FK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_options_transaction_transaction_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldOption_DDL_FK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOption_DDL_FK) ProtoMessage() {}

func (x *FieldOption_DDL_FK) ProtoReflect() protoreflect.Message {
	mi := &file_server_options_transaction_transaction_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOption_DDL_FK.ProtoReflect.Descriptor instead.
func (*FieldOption_DDL_FK) Descriptor() ([]byte, []int) {
	return file_server_options_transaction_transaction_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *FieldOption_DDL_FK) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *FieldOption_DDL_FK) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *FieldOption_DDL_FK) GetOnDelete() FieldOption_DDL_ReferenceOption {
	if x != nil {
		return x.OnDelete
	}
	return FieldOption_DDL_RESTRICT
}

func (x *FieldOption_DDL_FK) GetOnUpdate() FieldOption_DDL_ReferenceOption {
	if x != nil {
		return x.OnUpdate
	}
	return FieldOption_DDL_RESTRICT
}

var file_server_options_transaction_transaction_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOption)(nil),
		Field:         55001,
		Name:          "server.options.transaction.message",
		Tag:           "bytes,55001,opt,name=message",
		Filename:      "server/options/transaction/transaction.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOption)(nil),
		Field:         55002,
		Name:          "server.options.transaction.field",
		Tag:           "bytes,55002,opt,name=field",
		Filename:      "server/options/transaction/transaction.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional server.options.transaction.MessageOption message = 55001;
	E_Message = &file_server_options_transaction_transaction_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional server.options.transaction.FieldOption field = 55002;
	E_Field = &file_server_options_transaction_transaction_proto_extTypes[1]
)

var File_server_options_transaction_transaction_proto protoreflect.FileDescriptor

var file_server_options_transaction_transaction_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc3, 0x01, 0x0a,
	0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3f,
	0x0a, 0x03, 0x64, 0x64, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x44, 0x4c, 0x52, 0x03, 0x64, 0x64, 0x6c, 0x1a,
	0x71, 0x0a, 0x03, 0x44, 0x44, 0x4c, 0x12, 0x4d, 0x0a, 0x07, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x44, 0x44, 0x4c, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x07, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x65, 0x73, 0x1a, 0x1b, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12,
	0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65,
	0x79, 0x73, 0x22, 0xd0, 0x04, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x03, 0x64, 0x64, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x44, 0x4c, 0x52, 0x03, 0x64, 0x64,
	0x6c, 0x1a, 0x81, 0x04, 0x0a, 0x03, 0x44, 0x44, 0x4c, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x70, 0x6b, 0x12, 0x3e, 0x0a, 0x02, 0x66, 0x6b, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44,
	0x44, 0x4c, 0x2e, 0x46, 0x4b, 0x52, 0x02, 0x66, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x6e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x69, 0x73, 0x41,
	0x75, 0x74, 0x6f, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0f, 0x69, 0x73, 0x41, 0x75, 0x74, 0x6f, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x61, 0x73, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x68, 0x61, 0x73, 0x44, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x1a, 0xe4, 0x01, 0x0a, 0x02, 0x46, 0x4b, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x57, 0x0a, 0x08, 0x6f, 0x6e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3b, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x44, 0x4c, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x57, 0x0a, 0x08, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x3b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x44, 0x4c,
	0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x08, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x49, 0x0a, 0x0f, 0x52, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a,
	0x08, 0x52, 0x45, 0x53, 0x54, 0x52, 0x49, 0x43, 0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43,
	0x41, 0x53, 0x43, 0x41, 0x44, 0x45, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x45, 0x54, 0x5f,
	0x4e, 0x55, 0x4c, 0x4c, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x5f, 0x41, 0x43, 0x54,
	0x49, 0x4f, 0x4e, 0x10, 0x03, 0x3a, 0x66, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0xd9, 0xad, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x3a, 0x5e, 0x0a,
	0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xda, 0xad, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x52, 0x5a,
	0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x68, 0x61, 0x79,
	0x61, 0x6d, 0x69, 0x78, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67,
	0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_options_transaction_transaction_proto_rawDescOnce sync.Once
	file_server_options_transaction_transaction_proto_rawDescData = file_server_options_transaction_transaction_proto_rawDesc
)

func file_server_options_transaction_transaction_proto_rawDescGZIP() []byte {
	file_server_options_transaction_transaction_proto_rawDescOnce.Do(func() {
		file_server_options_transaction_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_options_transaction_transaction_proto_rawDescData)
	})
	return file_server_options_transaction_transaction_proto_rawDescData
}

var file_server_options_transaction_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_options_transaction_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_server_options_transaction_transaction_proto_goTypes = []interface{}{
	(FieldOption_DDL_ReferenceOption)(0), // 0: server.options.transaction.FieldOption.DDL.ReferenceOption
	(*MessageOption)(nil),                // 1: server.options.transaction.MessageOption
	(*FieldOption)(nil),                  // 2: server.options.transaction.FieldOption
	(*MessageOption_DDL)(nil),            // 3: server.options.transaction.MessageOption.DDL
	(*MessageOption_DDL_Index)(nil),      // 4: server.options.transaction.MessageOption.DDL.Index
	(*FieldOption_DDL)(nil),              // 5: server.options.transaction.FieldOption.DDL
	(*FieldOption_DDL_FK)(nil),           // 6: server.options.transaction.FieldOption.DDL.FK
	(*descriptorpb.MessageOptions)(nil),  // 7: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),    // 8: google.protobuf.FieldOptions
}
var file_server_options_transaction_transaction_proto_depIdxs = []int32{
	3,  // 0: server.options.transaction.MessageOption.ddl:type_name -> server.options.transaction.MessageOption.DDL
	5,  // 1: server.options.transaction.FieldOption.ddl:type_name -> server.options.transaction.FieldOption.DDL
	4,  // 2: server.options.transaction.MessageOption.DDL.indexes:type_name -> server.options.transaction.MessageOption.DDL.Index
	6,  // 3: server.options.transaction.FieldOption.DDL.fk:type_name -> server.options.transaction.FieldOption.DDL.FK
	0,  // 4: server.options.transaction.FieldOption.DDL.FK.onDelete:type_name -> server.options.transaction.FieldOption.DDL.ReferenceOption
	0,  // 5: server.options.transaction.FieldOption.DDL.FK.onUpdate:type_name -> server.options.transaction.FieldOption.DDL.ReferenceOption
	7,  // 6: server.options.transaction.message:extendee -> google.protobuf.MessageOptions
	8,  // 7: server.options.transaction.field:extendee -> google.protobuf.FieldOptions
	1,  // 8: server.options.transaction.message:type_name -> server.options.transaction.MessageOption
	2,  // 9: server.options.transaction.field:type_name -> server.options.transaction.FieldOption
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	8,  // [8:10] is the sub-list for extension type_name
	6,  // [6:8] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_server_options_transaction_transaction_proto_init() }
func file_server_options_transaction_transaction_proto_init() {
	if File_server_options_transaction_transaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_options_transaction_transaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_options_transaction_transaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_options_transaction_transaction_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageOption_DDL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_options_transaction_transaction_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageOption_DDL_Index); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_options_transaction_transaction_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldOption_DDL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_options_transaction_transaction_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldOption_DDL_FK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_options_transaction_transaction_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_server_options_transaction_transaction_proto_goTypes,
		DependencyIndexes: file_server_options_transaction_transaction_proto_depIdxs,
		EnumInfos:         file_server_options_transaction_transaction_proto_enumTypes,
		MessageInfos:      file_server_options_transaction_transaction_proto_msgTypes,
		ExtensionInfos:    file_server_options_transaction_transaction_proto_extTypes,
	}.Build()
	File_server_options_transaction_transaction_proto = out.File
	file_server_options_transaction_transaction_proto_rawDesc = nil
	file_server_options_transaction_transaction_proto_goTypes = nil
	file_server_options_transaction_transaction_proto_depIdxs = nil
}
