// Code generated by protoc-gen-all. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package api

import (
	"context"
	"encoding/json"

	"github.com/xhayamix/proto-gen-golang/pkg/cerrors"
	"github.com/xhayamix/proto-gen-golang/pkg/domain/port/api"
	"github.com/xhayamix/proto-gen-golang/pkg/domain/proto/client/api"
)

func (i *interactor) list(ctx context.Context) []api.Method {
	return []api.Method{
		api.UserServiceGetProfile,
	}
}

func (i *interactor) request(ctx context.Context, method api.Method, param string) (interface{}, error) {
	var result interface{}
	var err error
	switch method {
	case api.UserServiceGetProfile:
		req := &api.UserServiceGetProfileRequest{}
		if err := json.Unmarshal([]byte(param), req); err != nil {
			return "", cerrors.Wrap(err, cerrors.Internal)
		}
		result, err = i.api.UserServiceGetProfile(ctx, req)
		if err != nil {
			return "", cerrors.Wrap(err, cerrors.Internal)
		}
	default:
		return "", cerrors.Newf(cerrors.InvalidArgument, "APIが存在しません。 method = %q", method)
	}

	return result, nil
}
