// Code generated by protoc-gen-all. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package registry

import (
	"github.com/xhayamix/proto-gen-golang/pkg/infra/mysql/repository"
)

var MysqlRepositorySet = []interface{}{
	repository.NewUserRepository,
}
