// Code generated by protoc-gen-all. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

//go:generate mockgen -source=$GOFILE -destination=mock_$GOPACKAGE/mock_user.go
//go:generate goimports -w --local "github.com/xhayamix/proto-gen-golang" mock_$GOPACKAGE/mock_user.go

package transaction

import (
	"context"

	"github.com/xhayamix/proto-gen-golang/pkg/domain/database"
	"github.com/xhayamix/proto-gen-golang/pkg/domain/entity/transaction"
)

type UserRepository interface {
	SelectAll(ctx context.Context) (transaction.UserSlice, error)
	SelectAllOffset(ctx context.Context, offset, limit int) (transaction.UserSlice, error)
	SelectAllByTx(ctx context.Context, tx database.ROTx) (transaction.UserSlice, error)
	SelectByPK(ctx context.Context, ID_ string) (*transaction.User, error)
	SelectByTx(ctx context.Context, tx database.ROTx, ID_ string) (*transaction.User, error)
	SelectByPKs(ctx context.Context, pks transaction.UserPKs) (transaction.UserSlice, error)
	SearchByID(ctx context.Context, searchText string, limit int) ([]string, error)
	Insert(ctx context.Context, tx database.RWTx, entity *transaction.User) error
	BulkInsert(ctx context.Context, tx database.RWTx, entities transaction.UserSlice, replace bool) error
	Update(ctx context.Context, tx database.RWTx, entity *transaction.User) error
	Delete(ctx context.Context, tx database.RWTx, entity *transaction.User) error
	BulkDelete(ctx context.Context, tx database.RWTx, entities transaction.UserSlice) error
	DeleteAll(ctx context.Context, tx database.RWTx) error
}
