// Code generated by protoc-gen-all. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package responsecache

import (
	"github.com/xhayamix/proto-gen-golang/pkg/domain/proto/client/api"
)

var enableResponseCacheMethodMap = map[string]interface{}{
	"/client.api.UserService/GetProfile": (*api.GetProfileResponse)(nil),
}
