// Code generated by protoc-gen-all. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package registry

import (
	"google.golang.org/grpc"
)

func registerServer(s *grpc.Server) func() {
	return func() {
	}
}
