// Code generated by protoc-gen-all. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

//go:generate mockgen -source=$GOFILE -destination=mock_$GOPACKAGE/mock_api.go
//go:generate goimports -w --local "github.com/xhayamix/proto-gen-golang" mock_$GOPACKAGE/mock_api.go
package api

import (
	"context"

	"github.com/xhayamix/proto-gen-golang/pkg/domain/proto/client/api"
)

type Method string

var (
	// UserService
	UserServiceGetProfile Method = "UserServiceGetProfile"
)

type API interface {
	// UserServiceGetProfile GetProfile
	UserServiceGetProfile(ctx context.Context, req *api.UserServiceGetProfileRequest) (*api.UserServiceGetProfileResponse, error)
	// Close クローズ処理
	Close() error
}
