// Code generated by protoc-gen-all. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package api

import (
	"github.com/xhayamix/proto-gen-golang/pkg/domain/proto/client/api/common"
)

func (m *GetProfileResponse) SetCommonResponse(res *common.Response) {
	m.CommonResponse = res
}
