// Code generated by protoc-gen-all. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

enum ActiveUserType {
  "" = 0,
  provisional = 1,
  Active = 2,
  Deleted = 99,
}

namespace ActiveUserType {
  export function values(): ActiveUserType[] {
    return [
      ActiveUserType.provisional,
      ActiveUserType.Active,
      ActiveUserType.Deleted,
    ];
  }

  export function strings(): string[] {
    return [
      "provisional",
      "Active",
      "Deleted",
    ];
  }

  export function toEnum(s: string): ActiveUserType {
    switch (s) {
      case "provisional": return ActiveUserType.provisional;
      case "Active": return ActiveUserType.Active;
      case "Deleted": return ActiveUserType.Deleted;
      default: return ActiveUserType[""];
    }
  }

  export function toComment(v: ActiveUserType): string {
    switch (v) {
      case ActiveUserType.provisional: return "仮登録";
      case ActiveUserType.Active: return "アクティブユーザー";
      case ActiveUserType.Deleted: return "アカウント削除済み";
      default: return "";
    }
  }
}

export { ActiveUserType };
