// Code generated by protoc-gen-all. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: server/enums/enums_gen.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActiveUserType int32

const (
	ActiveUserType_ActiveUserType_Unknown ActiveUserType = 0
	// 仮登録
	ActiveUserType_ActiveUserType_provisional ActiveUserType = 1
	// アクティブユーザー
	ActiveUserType_ActiveUserType_Active ActiveUserType = 2
	// アカウント削除済み
	ActiveUserType_ActiveUserType_Deleted ActiveUserType = 99
)

// Enum value maps for ActiveUserType.
var (
	ActiveUserType_name = map[int32]string{
		0:  "ActiveUserType_Unknown",
		1:  "ActiveUserType_provisional",
		2:  "ActiveUserType_Active",
		99: "ActiveUserType_Deleted",
	}
	ActiveUserType_value = map[string]int32{
		"ActiveUserType_Unknown":     0,
		"ActiveUserType_provisional": 1,
		"ActiveUserType_Active":      2,
		"ActiveUserType_Deleted":     99,
	}
)

func (x ActiveUserType) Enum() *ActiveUserType {
	p := new(ActiveUserType)
	*p = x
	return p
}

func (x ActiveUserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActiveUserType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_enums_enums_gen_proto_enumTypes[0].Descriptor()
}

func (ActiveUserType) Type() protoreflect.EnumType {
	return &file_server_enums_enums_gen_proto_enumTypes[0]
}

func (x ActiveUserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActiveUserType.Descriptor instead.
func (ActiveUserType) EnumDescriptor() ([]byte, []int) {
	return file_server_enums_enums_gen_proto_rawDescGZIP(), []int{0}
}

var File_server_enums_enums_gen_proto protoreflect.FileDescriptor

var file_server_enums_enums_gen_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f, 0x65,
	0x6e, 0x75, 0x6d, 0x73, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2a, 0x83, 0x01, 0x0a,
	0x0e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1a, 0x0a, 0x16, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x10, 0x63, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x78, 0x68, 0x61, 0x79, 0x61, 0x6d, 0x69, 0x78, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d,
	0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_enums_enums_gen_proto_rawDescOnce sync.Once
	file_server_enums_enums_gen_proto_rawDescData = file_server_enums_enums_gen_proto_rawDesc
)

func file_server_enums_enums_gen_proto_rawDescGZIP() []byte {
	file_server_enums_enums_gen_proto_rawDescOnce.Do(func() {
		file_server_enums_enums_gen_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_enums_enums_gen_proto_rawDescData)
	})
	return file_server_enums_enums_gen_proto_rawDescData
}

var file_server_enums_enums_gen_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_enums_enums_gen_proto_goTypes = []interface{}{
	(ActiveUserType)(0), // 0: server.enums.ActiveUserType
}
var file_server_enums_enums_gen_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_enums_enums_gen_proto_init() }
func file_server_enums_enums_gen_proto_init() {
	if File_server_enums_enums_gen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_enums_enums_gen_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_enums_enums_gen_proto_goTypes,
		DependencyIndexes: file_server_enums_enums_gen_proto_depIdxs,
		EnumInfos:         file_server_enums_enums_gen_proto_enumTypes,
	}.Build()
	File_server_enums_enums_gen_proto = out.File
	file_server_enums_enums_gen_proto_rawDesc = nil
	file_server_enums_enums_gen_proto_goTypes = nil
	file_server_enums_enums_gen_proto_depIdxs = nil
}
